info:
  setting: 'od_val_refuge/1_7/100gamma'
  description: 'sup_100GAMMA,700REFUGE'
MODEL:
  sup: False
  NUM_CLASSES: 2
  batch_size: 8
  epochs: 100
  lr: 0.002 # 0.004/16*batch_size
  crop_size: 512
  dataset: 'sup'
  data_root: './data/fundus_datasets/od_oc/WACV/REFUGE_cross_new/'
  backbone: 'resnet50'
  model: 'deeplabv3plus'
  labeled_id_path: 'dataset/splits/sup/GAMMA100_labeled.txt'
  labeled_id_path_2: 'dataset/splits/sup/REFUGE100_labeled.txt'
  stage1_ckpt_path: 'experiments/sup/GAMMA100_sup/models/train_mIoUTdeeplabv3plus_resnet50_90.10.pth'
  stage1: False
  stage2: True
  stage2_prototype: False
  sup_uda: True
  stage2_prototype_useTeacher: True
  stage3: False
  stage4: False
  stage5: False